### ISSUE TITLE
Callbacks

### ISSUE THREAD

**Issue by simi** [vodkabears/galereya#11]
Hello, it will be cool to add more callbacks.

I'm now using `onSliderClose()` and `onSliderChange(index, data)`.

You can check https://github.com/simi/rouming-ng/blob/4406676a79bf2682248df10dc19fde9850852bda/js/vendor/jquery.galereya.dev.js for my naive implementation.

I can send you PR if you want.

Also do you have any plan to add `changeSlide(index)` or any idea how to achieve this?

Anyway, thanks for this awesome script! :heart:

**Comment by terrysmyth** [comment]
I want to get rid of the ALL category but the callback doesnt seem to work. Help would be appreciated. Thanks

$('#galExample').galereya({
		noCategoryName: 'all',
	});

This is what i have.
